FacturaElectronica\CodigoType:
    properties:
        tipo:
            expose: true
            access_type: public_method
            serialized_name: Tipo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipo
                setter: setTipo
            type: string
        codigo:
            expose: true
            access_type: public_method
            serialized_name: Codigo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigo
                setter: setCodigo
            type: string
