FacturaElectronica\CodigoMonedaType:
    properties:
        codigoMoneda:
            expose: true
            access_type: public_method
            serialized_name: CodigoMoneda
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoMoneda
                setter: setCodigoMoneda
            type: string
        tipoCambio:
            expose: true
            access_type: public_method
            serialized_name: TipoCambio
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoCambio
                setter: setTipoCambio
            type: float
