FacturaElectronica\DescuentoType:
    properties:
        montoDescuento:
            expose: true
            access_type: public_method
            serialized_name: MontoDescuento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoDescuento
                setter: setMontoDescuento
            type: float
        codigoDescuento:
            expose: true
            access_type: public_method
            serialized_name: CodigoDescuento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoDescuento
                setter: setCodigoDescuento
            type: string
        codigoDescuentoOTRO:
            expose: true
            access_type: public_method
            serialized_name: CodigoDescuentoOTRO
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoDescuentoOTRO
                setter: setCodigoDescuentoOTRO
            type: string
        naturalezaDescuento:
            expose: true
            access_type: public_method
            serialized_name: NaturalezaDescuento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNaturalezaDescuento
                setter: setNaturalezaDescuento
            type: string
