FacturaElectronica\EmisorType:
    properties:
        nombre:
            expose: true
            access_type: public_method
            serialized_name: Nombre
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNombre
                setter: setNombre
            type: string
        identificacion:
            expose: true
            access_type: public_method
            serialized_name: Identificacion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getIdentificacion
                setter: setIdentificacion
            type: FacturaElectronica\IdentificacionType
        registrofiscal8707:
            expose: true
            access_type: public_method
            serialized_name: Registrofiscal8707
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getRegistrofiscal8707
                setter: setRegistrofiscal8707
            type: string
        nombreComercial:
            expose: true
            access_type: public_method
            serialized_name: NombreComercial
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNombreComercial
                setter: setNombreComercial
            type: string
        ubicacion:
            expose: true
            access_type: public_method
            serialized_name: Ubicacion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getUbicacion
                setter: setUbicacion
            type: FacturaElectronica\UbicacionType
        telefono:
            expose: true
            access_type: public_method
            serialized_name: Telefono
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTelefono
                setter: setTelefono
            type: FacturaElectronica\TelefonoType
        correoElectronico:
            expose: true
            access_type: public_method
            serialized_name: CorreoElectronico
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCorreoElectronico
                setter: setCorreoElectronico
            xml_list:
                inline: true
                entry_name: CorreoElectronico
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<string>
