FacturaElectronica\ExoneracionType:
    properties:
        tipoDocumentoEX1:
            expose: true
            access_type: public_method
            serialized_name: TipoDocumentoEX1
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocumentoEX1
                setter: setTipoDocumentoEX1
            type: string
        tipoDocumentoOTRO:
            expose: true
            access_type: public_method
            serialized_name: TipoDocumentoOTRO
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocumentoOTRO
                setter: setTipoDocumentoOTRO
            type: string
        numeroDocumento:
            expose: true
            access_type: public_method
            serialized_name: NumeroDocumento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumeroDocumento
                setter: setNumeroDocumento
            type: string
        articulo:
            expose: true
            access_type: public_method
            serialized_name: Articulo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getArticulo
                setter: setArticulo
            type: integer
        inciso:
            expose: true
            access_type: public_method
            serialized_name: Inciso
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getInciso
                setter: setInciso
            type: integer
        nombreInstitucion:
            expose: true
            access_type: public_method
            serialized_name: NombreInstitucion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNombreInstitucion
                setter: setNombreInstitucion
            type: string
        nombreInstitucionOtros:
            expose: true
            access_type: public_method
            serialized_name: NombreInstitucionOtros
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNombreInstitucionOtros
                setter: setNombreInstitucionOtros
            type: string
        fechaEmisionEX:
            expose: true
            access_type: public_method
            serialized_name: FechaEmisionEX
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getFechaEmisionEX
                setter: setFechaEmisionEX
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        tarifaExonerada:
            expose: true
            access_type: public_method
            serialized_name: TarifaExonerada
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTarifaExonerada
                setter: setTarifaExonerada
            type: float
        montoExoneracion:
            expose: true
            access_type: public_method
            serialized_name: MontoExoneracion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoExoneracion
                setter: setMontoExoneracion
            type: float
