FacturaElectronica\FacturaElectronica\OtrosAType\OtroContenidoAType:
    properties:
        codigo:
            expose: true
            access_type: public_method
            serialized_name: codigo
            accessor:
                getter: getCodigo
                setter: setCodigo
            xml_attribute: true
            type: string
