FacturaElectronica\FacturaElectronica\ResumenFacturaAType\MedioPagoAType:
    properties:
        tipoMedioPago:
            expose: true
            access_type: public_method
            serialized_name: TipoMedioPago
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoMedioPago
                setter: setTipoMedioPago
            type: string
        medioPagoOtros:
            expose: true
            access_type: public_method
            serialized_name: MedioPagoOtros
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMedioPagoOtros
                setter: setMedioPagoOtros
            type: string
        totalMedioPago:
            expose: true
            access_type: public_method
            serialized_name: TotalMedioPago
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTotalMedioPago
                setter: setTotalMedioPago
            type: float
