FacturaElectronica\FacturaElectronica\OtrosAType\OtroTextoAType:
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
        codigo:
            expose: true
            access_type: public_method
            serialized_name: codigo
            accessor:
                getter: getCodigo
                setter: setCodigo
            xml_attribute: true
            type: string
