FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType\DescuentoSurtidoAType:
    properties:
        montoDescuentoSurtido:
            expose: true
            access_type: public_method
            serialized_name: MontoDescuentoSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoDescuentoSurtido
                setter: setMontoDescuentoSurtido
            type: float
        codigoDescuentoSurtido:
            expose: true
            access_type: public_method
            serialized_name: CodigoDescuentoSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoDescuentoSurtido
                setter: setCodigoDescuentoSurtido
            type: string
        descuentoSurtidoOtros:
            expose: true
            access_type: public_method
            serialized_name: DescuentoSurtidoOtros
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDescuentoSurtidoOtros
                setter: setDescuentoSurtidoOtros
            type: string
