FacturaElectronica\FacturaElectronica\OtrosAType:
    properties:
        otroTexto:
            expose: true
            access_type: public_method
            serialized_name: OtroTexto
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getOtroTexto
                setter: setOtroTexto
            xml_list:
                inline: true
                entry_name: OtroTexto
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<string>
        otroContenido:
            expose: true
            access_type: public_method
            serialized_name: OtroContenido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getOtroContenido
                setter: setOtroContenido
            xml_list:
                inline: true
                entry_name: OtroContenido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<string>
