FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType:
    properties:
        numeroLinea:
            expose: true
            access_type: public_method
            serialized_name: NumeroLinea
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumeroLinea
                setter: setNumeroLinea
            type: integer
        codigoCABYS:
            expose: true
            access_type: public_method
            serialized_name: CodigoCABYS
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoCABYS
                setter: setCodigoCABYS
            type: string
        codigoComercial:
            expose: true
            access_type: public_method
            serialized_name: CodigoComercial
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoComercial
                setter: setCodigoComercial
            xml_list:
                inline: true
                entry_name: CodigoComercial
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\CodigoType>
        cantidad:
            expose: true
            access_type: public_method
            serialized_name: Cantidad
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCantidad
                setter: setCantidad
            type: float
        unidadMedida:
            expose: true
            access_type: public_method
            serialized_name: UnidadMedida
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getUnidadMedida
                setter: setUnidadMedida
            type: string
        tipoTransaccion:
            expose: true
            access_type: public_method
            serialized_name: TipoTransaccion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoTransaccion
                setter: setTipoTransaccion
            type: string
        unidadMedidaComercial:
            expose: true
            access_type: public_method
            serialized_name: UnidadMedidaComercial
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getUnidadMedidaComercial
                setter: setUnidadMedidaComercial
            type: string
        detalle:
            expose: true
            access_type: public_method
            serialized_name: Detalle
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDetalle
                setter: setDetalle
            type: string
        numeroVINoSerie:
            expose: true
            access_type: public_method
            serialized_name: NumeroVINoSerie
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumeroVINoSerie
                setter: setNumeroVINoSerie
            xml_list:
                inline: true
                entry_name: NumeroVINoSerie
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<string>
        registroMedicamento:
            expose: true
            access_type: public_method
            serialized_name: RegistroMedicamento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getRegistroMedicamento
                setter: setRegistroMedicamento
            type: string
        formaFarmaceutica:
            expose: true
            access_type: public_method
            serialized_name: FormaFarmaceutica
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getFormaFarmaceutica
                setter: setFormaFarmaceutica
            type: string
        detalleSurtido:
            expose: true
            access_type: public_method
            serialized_name: DetalleSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDetalleSurtido
                setter: setDetalleSurtido
            type: array<FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType>
            xml_list:
                inline: false
                skip_when_empty: true
                entry_name: LineaDetalleSurtido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
        precioUnitario:
            expose: true
            access_type: public_method
            serialized_name: PrecioUnitario
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getPrecioUnitario
                setter: setPrecioUnitario
            type: float
        montoTotal:
            expose: true
            access_type: public_method
            serialized_name: MontoTotal
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoTotal
                setter: setMontoTotal
            type: float
        descuento:
            expose: true
            access_type: public_method
            serialized_name: Descuento
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDescuento
                setter: setDescuento
            xml_list:
                inline: true
                entry_name: Descuento
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\DescuentoType>
        subTotal:
            expose: true
            access_type: public_method
            serialized_name: SubTotal
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getSubTotal
                setter: setSubTotal
            type: float
        iVACobradoFabrica:
            expose: true
            access_type: public_method
            serialized_name: IVACobradoFabrica
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getIVACobradoFabrica
                setter: setIVACobradoFabrica
            type: string
        baseImponible:
            expose: true
            access_type: public_method
            serialized_name: BaseImponible
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getBaseImponible
                setter: setBaseImponible
            type: float
        impuesto:
            expose: true
            access_type: public_method
            serialized_name: Impuesto
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getImpuesto
                setter: setImpuesto
            xml_list:
                inline: true
                entry_name: Impuesto
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\ImpuestoType>
        impuestoAsumidoEmisorFabrica:
            expose: true
            access_type: public_method
            serialized_name: ImpuestoAsumidoEmisorFabrica
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getImpuestoAsumidoEmisorFabrica
                setter: setImpuestoAsumidoEmisorFabrica
            type: float
        impuestoNeto:
            expose: true
            access_type: public_method
            serialized_name: ImpuestoNeto
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getImpuestoNeto
                setter: setImpuestoNeto
            type: float
        montoTotalLinea:
            expose: true
            access_type: public_method
            serialized_name: MontoTotalLinea
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoTotalLinea
                setter: setMontoTotalLinea
            type: float
