FacturaElectronica\FacturaElectronica\InformacionReferenciaAType:
    properties:
        tipoDocIR:
            expose: true
            access_type: public_method
            serialized_name: TipoDocIR
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocIR
                setter: setTipoDocIR
            type: string
        tipoDocRefOTRO:
            expose: true
            access_type: public_method
            serialized_name: TipoDocRefOTRO
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocRefOTRO
                setter: setTipoDocRefOTRO
            type: string
        numero:
            expose: true
            access_type: public_method
            serialized_name: Numero
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumero
                setter: setNumero
            type: string
        fechaEmisionIR:
            expose: true
            access_type: public_method
            serialized_name: FechaEmisionIR
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getFechaEmisionIR
                setter: setFechaEmisionIR
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        codigo:
            expose: true
            access_type: public_method
            serialized_name: Codigo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigo
                setter: setCodigo
            type: string
        codigoReferenciaOTRO:
            expose: true
            access_type: public_method
            serialized_name: CodigoReferenciaOTRO
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoReferenciaOTRO
                setter: setCodigoReferenciaOTRO
            type: string
        razon:
            expose: true
            access_type: public_method
            serialized_name: Razon
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getRazon
                setter: setRazon
            type: string
