FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType:
    properties:
        lineaDetalleSurtido:
            expose: true
            access_type: public_method
            serialized_name: LineaDetalleSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getLineaDetalleSurtido
                setter: setLineaDetalleSurtido
            xml_list:
                inline: true
                entry_name: LineaDetalleSurtido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType>
