FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType:
    properties:
        codigoCABYSSurtido:
            expose: true
            access_type: public_method
            serialized_name: CodigoCABYSSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoCABYSSurtido
                setter: setCodigoCABYSSurtido
            type: string
        codigoComercialSurtido:
            expose: true
            access_type: public_method
            serialized_name: CodigoComercialSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoComercialSurtido
                setter: setCodigoComercialSurtido
            xml_list:
                inline: true
                entry_name: CodigoComercialSurtido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType\CodigoComercialSurtidoAType>
        cantidadSurtido:
            expose: true
            access_type: public_method
            serialized_name: CantidadSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCantidadSurtido
                setter: setCantidadSurtido
            type: float
        unidadMedidaSurtido:
            expose: true
            access_type: public_method
            serialized_name: UnidadMedidaSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getUnidadMedidaSurtido
                setter: setUnidadMedidaSurtido
            type: string
        unidadMedidaComercialSurtido:
            expose: true
            access_type: public_method
            serialized_name: UnidadMedidaComercialSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getUnidadMedidaComercialSurtido
                setter: setUnidadMedidaComercialSurtido
            type: string
        detalleSurtido:
            expose: true
            access_type: public_method
            serialized_name: DetalleSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDetalleSurtido
                setter: setDetalleSurtido
            type: string
        precioUnitarioSurtido:
            expose: true
            access_type: public_method
            serialized_name: PrecioUnitarioSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getPrecioUnitarioSurtido
                setter: setPrecioUnitarioSurtido
            type: float
        montoTotalSurtido:
            expose: true
            access_type: public_method
            serialized_name: MontoTotalSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoTotalSurtido
                setter: setMontoTotalSurtido
            type: float
        descuentoSurtido:
            expose: true
            access_type: public_method
            serialized_name: DescuentoSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDescuentoSurtido
                setter: setDescuentoSurtido
            xml_list:
                inline: true
                entry_name: DescuentoSurtido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType\DescuentoSurtidoAType>
        subTotalSurtido:
            expose: true
            access_type: public_method
            serialized_name: SubTotalSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getSubTotalSurtido
                setter: setSubTotalSurtido
            type: float
        iVACobradoFabricaSurtido:
            expose: true
            access_type: public_method
            serialized_name: IVACobradoFabricaSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getIVACobradoFabricaSurtido
                setter: setIVACobradoFabricaSurtido
            type: string
        baseImponibleSurtido:
            expose: true
            access_type: public_method
            serialized_name: BaseImponibleSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getBaseImponibleSurtido
                setter: setBaseImponibleSurtido
            type: float
        impuestoSurtido:
            expose: true
            access_type: public_method
            serialized_name: ImpuestoSurtido
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getImpuestoSurtido
                setter: setImpuestoSurtido
            xml_list:
                inline: true
                entry_name: ImpuestoSurtido
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            type: array<FacturaElectronica\FacturaElectronica\DetalleServicioAType\LineaDetalleAType\DetalleSurtidoAType\LineaDetalleSurtidoAType\ImpuestoSurtidoAType>
