FacturaElectronica\IdentificacionType:
    properties:
        tipo:
            expose: true
            access_type: public_method
            serialized_name: Tipo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipo
                setter: setTipo
            type: string
        numero:
            expose: true
            access_type: public_method
            serialized_name: Numero
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumero
                setter: setNumero
            type: string
