FacturaElectronica\ImpuestoType\DatosImpuestoEspecificoAType:
    properties:
        cantidadUnidadMedida:
            expose: true
            access_type: public_method
            serialized_name: CantidadUnidadMedida
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCantidadUnidadMedida
                setter: setCantidadUnidadMedida
            type: float
        porcentaje:
            expose: true
            access_type: public_method
            serialized_name: Porcentaje
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getPorcentaje
                setter: setPorcentaje
            type: float
        proporcion:
            expose: true
            access_type: public_method
            serialized_name: Proporcion
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getProporcion
                setter: setProporcion
            type: float
        volumenUnidadConsumo:
            expose: true
            access_type: public_method
            serialized_name: VolumenUnidadConsumo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getVolumenUnidadConsumo
                setter: setVolumenUnidadConsumo
            type: float
        impuestoUnidad:
            expose: true
            access_type: public_method
            serialized_name: ImpuestoUnidad
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getImpuestoUnidad
                setter: setImpuestoUnidad
            type: float
