FacturaElectronica\OtrosCargosType:
    properties:
        tipoDocumentoOC:
            expose: true
            access_type: public_method
            serialized_name: TipoDocumentoOC
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocumentoOC
                setter: setTipoDocumentoOC
            type: string
        tipoDocumentoOTROS:
            expose: true
            access_type: public_method
            serialized_name: TipoDocumentoOTROS
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getTipoDocumentoOTROS
                setter: setTipoDocumentoOTROS
            type: string
        identificacionTercero:
            expose: true
            access_type: public_method
            serialized_name: IdentificacionTercero
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getIdentificacionTercero
                setter: setIdentificacionTercero
            type: FacturaElectronica\IdentificacionType
        nombreTercero:
            expose: true
            access_type: public_method
            serialized_name: NombreTercero
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNombreTercero
                setter: setNombreTercero
            type: string
        detalle:
            expose: true
            access_type: public_method
            serialized_name: Detalle
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDetalle
                setter: setDetalle
            type: string
        porcentajeOC:
            expose: true
            access_type: public_method
            serialized_name: PorcentajeOC
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getPorcentajeOC
                setter: setPorcentajeOC
            type: float
        montoCargo:
            expose: true
            access_type: public_method
            serialized_name: MontoCargo
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getMontoCargo
                setter: setMontoCargo
            type: float
