FacturaElectronica\TelefonoType:
    properties:
        codigoPais:
            expose: true
            access_type: public_method
            serialized_name: CodigoPais
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCodigoPais
                setter: setCodigoPais
            type: integer
        numTelefono:
            expose: true
            access_type: public_method
            serialized_name: NumTelefono
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getNumTelefono
                setter: setNumTelefono
            type: integer
