FacturaElectronica\UbicacionType:
    properties:
        provincia:
            expose: true
            access_type: public_method
            serialized_name: Provincia
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getProvincia
                setter: setProvincia
            type: integer
        canton:
            expose: true
            access_type: public_method
            serialized_name: Canton
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getCanton
                setter: setCanton
            type: integer
        distrito:
            expose: true
            access_type: public_method
            serialized_name: Distrito
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getDistrito
                setter: setDistrito
            type: integer
        barrio:
            expose: true
            access_type: public_method
            serialized_name: Barrio
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getBarrio
                setter: setBarrio
            type: string
        otrasSenas:
            expose: true
            access_type: public_method
            serialized_name: OtrasSenas
            xml_element:
                namespace: 'https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/facturaElectronica'
            accessor:
                getter: getOtrasSenas
                setter: setOtrasSenas
            type: string
